# Generated by Django 5.0.2 on 2024-08-20 21:06

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        help_text="유저 아이디", primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="유저 이메일", max_length=30, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="유저 이름", max_length=16)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="0: 남자, 1: 여자, 2: 알수없음", null=True
                    ),
                ),
                (
                    "birth_date",
                    models.CharField(
                        blank=True,
                        help_text="생년월일 (YYYYMMDD)",
                        max_length=8,
                        null=True,
                    ),
                ),
                ("zip_code", models.CharField(help_text="고객 ZIP 코드", max_length=8)),
                (
                    "resident_code",
                    models.CharField(help_text="고객 주민등록번호", max_length=16),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="고객 주소", max_length=255, null=True
                    ),
                ),
                (
                    "address_detail",
                    models.CharField(
                        blank=True,
                        help_text="고객 상세 주소",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        blank=True, help_text="고객 CI 값", max_length=128, null=True
                    ),
                ),
                (
                    "di",
                    models.CharField(
                        blank=True, help_text="고객 DI 값", max_length=256, null=True
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="고객 비밀번호 해쉬 값(sha3_256)", max_length=128
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="고객 휴대전화 번호(010XXXXYYYY)", max_length=16
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="활성화 여부(0: 활성화, 1: 비활성화)"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "get_latest_by": "id",
            },
        ),
    ]
