# Generated by Django 5.0.2 on 2024-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.CharField(help_text="생년월일 (YYYYMMDD)", max_length=8),
        ),
        migrations.AlterField(
            model_name="user",
            name="ci",
            field=models.CharField(help_text="고객 CI 값", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                help_text="0: 남자, 1: 여자, 2: 알수없음"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="고객 휴대전화 번호(010XXXXYYYY)",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="resident_code",
            field=models.CharField(
                blank=True, help_text="고객 주민등록번호", max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="고객 ZIP 코드", max_length=8, null=True
            ),
        ),
    ]
